name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Smoke-test that Index.js loads
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          node -e "require('./Index.js'); console.log('Loaded OK'); process.exit(0)"
